version: '3.8'
services:
  db-justificative:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_DATABASE=justificative
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    ports:
      - 3308:3306