server:
  port: 8080
spring:
  devtools:
    restart:
      aditional-paths: src/main/java
  application:
    name: justificative-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOSTNAME:localhost}:${DB_PORT:3308}/${DB_NAME:justificative}?autorReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USR:root}
    password: ${DB_PSW:root}
  jpa:
    show-sql: true
    hibernate:
      dialect: MySQL8Dialect
      ddl-auto: create
keycloak:
  realm: web
  authServerUrl: http://localhost:9000 # Aqui se debe cambiar al puerto que se le asigno a Keycloak
  resource: spring-key
  publicClient: true
  sslRequired: external
  bearerOnly: true
  useResourceRoleMappings: true